import { QuestionData } from './types';

export const PRIZE_LADDER = [
  500,
  1000,
  2000,
  3000,
  5000,      // Checkpoint 1 (несгораемая сумма)
  10000,
  15000,
  25000,
  50000,
  100000,    // Checkpoint 2 (несгораемая сумма)
  150000,
  250000,
  400000,
  600000,
  1000000,   // Главный приз: 1 000 000 €
];

export const ALL_QUESTIONS: QuestionData[] = [
  // --- 🎬 Cine — Кинотеатр (1 - 10) ---
  {
    id: 1,
    category: 'cine',
    categoryTitleEs: '🎬 Cine',
    categoryTitleRu: 'Кинотеатр',
    tense: 'Presente',
    tenseExplanationRu: 'Llegas (ты приходишь) / no sabes (не знаешь) / ponen (ставят/показывают) / haces (делаешь) — настоящее время (Presente de Indicativo).',
    questionEs: 'Llegas al cine y no sabes en qué sala ponen tu película. ¿Qué haces?',
    questionRu: 'Ты приходишь в кинотеатр и не знаешь, в каком зале идёт твой фильм. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Entro en cualquier sala.', ru: 'Захожу в любой зал.' },
      { id: 'B', es: 'Pregunto a un empleado.', ru: 'Спрашиваю у сотрудника.' },
      { id: 'C', es: 'Me voy a casa.', ru: 'Ухожу домой.' },
      { id: 'D', es: 'Compro otra entrada.', ru: 'Покупаю другой билет.' },
    ],
    correctAnswer: 'B',
    explanationRu: 'Самое логичное и вежливое действие — обратиться к сотруднику кинотеатра («Pregunto a un empleado»).',
    prizeMoney: 500,
  },
  {
    id: 2,
    category: 'cine',
    categoryTitleEs: '🎬 Cine',
    categoryTitleRu: 'Кинотеатр',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has comprado (ты купил) — прошедшее завершённое время (Pretérito Perfecto Compuesto: haber + participio).',
    questionEs: 'Has comprado una entrada, pero no encuentras tu asiento. ¿Qué haces?',
    questionRu: 'Ты купил билет, но не можешь найти своё место. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Miro el número de la entrada y busco mi fila.', ru: 'Смотрю номер билета и ищу свой ряд.' },
      { id: 'B', es: 'Me siento en cualquier sitio.', ru: 'Сажусь на любое место.' },
      { id: 'C', es: 'Salgo del cine.', ru: 'Выхожу из кинотеатра.' },
      { id: 'D', es: 'Rompo la entrada.', ru: 'Рву билет.' },
    ],
    correctAnswer: 'A',
    explanationRu: 'В билете указан номер ряда (fila) и места (asiento), поэтому сначала стоит свериться с билетом.',
    prizeMoney: 1000,
  },
  {
    id: 3,
    category: 'cine',
    categoryTitleEs: '🎬 Cine',
    categoryTitleRu: 'Кинотеатр',
    tense: 'Presente + Pretérito Perfecto',
    tenseExplanationRu: 'Ha empezado (начался — Pretérito Perfecto), llegas (приходишь — Presente).',
    questionEs: 'La película ya ha empezado y llegas tarde. ¿Qué haces?',
    questionRu: 'Фильм уже начался, а ты опоздал. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Hablo muy alto.', ru: 'Говорю очень громко.' },
      { id: 'B', es: 'Entro haciendo ruido.', ru: 'Вхожу шумно.' },
      { id: 'C', es: 'Entro en silencio y busco mi asiento.', ru: 'Вхожу в тишине и ищу своё место.' },
      { id: 'D', es: 'Enciendo la luz.', ru: 'Включаю свет.' },
    ],
    correctAnswer: 'C',
    explanationRu: 'Чтобы не мешать другим зрителям в зале, нужно зайти тихо («entro en silencio»).',
    prizeMoney: 2000,
  },
  {
    id: 4,
    category: 'cine',
    categoryTitleEs: '🎬 Cine',
    categoryTitleRu: 'Кинотеатр',
    tense: 'Presente',
    tenseExplanationRu: 'Empieza a sonar (начинает звонить) / haces (делаешь) — Presente.',
    questionEs: 'Durante la película tu teléfono empieza a sonar. ¿Qué haces?',
    questionRu: 'Во время фильма у тебя начинает звонить телефон. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Contesto en voz alta.', ru: 'Отвечаю громким голосом.' },
      { id: 'B', es: 'Lo silencio.', ru: 'Ставлю его на беззвучный режим.' },
      { id: 'C', es: 'Pongo música.', ru: 'Включаю музыку.' },
      { id: 'D', es: 'Se lo doy a otra persona.', ru: 'Отдаю его другому человеку.' },
    ],
    correctAnswer: 'B',
    explanationRu: '«Silenciar el teléfono» означает выключить звук / перевести в беззвучный режим.',
    prizeMoney: 3000,
  },
  {
    id: 5,
    category: 'cine',
    categoryTitleEs: '🎬 Cine',
    categoryTitleRu: 'Кинотеатр',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has comprado (ты купил), se te han caído (у тебя упали) — Pretérito Perfecto.',
    questionEs: 'Has comprado palomitas, pero se te han caído al suelo. ¿Qué haces?',
    questionRu: 'Ты купил попкорн, но он упал на пол. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Lo dejo todo allí.', ru: 'Оставляю всё там.' },
      { id: 'B', es: 'Aviso a un empleado y recojo lo que puedo.', ru: 'Предупреждаю сотрудника и убираю то, что могу.' },
      { id: 'C', es: 'Como las palomitas del suelo.', ru: 'Ем попкорн с пола.' },
      { id: 'D', es: 'Echo más al suelo.', ru: 'Бросаю ещё больше на пол.' },
    ],
    correctAnswer: 'B',
    explanationRu: 'Культурное поведение: предупредить персонал зала («aviso a un empleado») и подобрать крупный мусор.',
    prizeMoney: 5000,
  },
  {
    id: 6,
    category: 'cine',
    categoryTitleEs: '🎬 Cine',
    categoryTitleRu: 'Кинотеатр',
    tense: 'Presente',
    tenseExplanationRu: 'No entiendes (ты не понимаешь) — Presente от неправильного глагола entender (e -> ie).',
    questionEs: 'No entiendes una parte de la película. ¿Qué haces?',
    questionRu: 'Ты не понял часть фильма. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Grito una pregunta.', ru: 'Выкрикиваю вопрос.' },
      { id: 'B', es: 'Pregunto a mi amigo después de la película.', ru: 'Спрашиваю у друга после фильма.' },
      { id: 'C', es: 'Paro la película.', ru: 'Останавливаю фильм.' },
      { id: 'D', es: 'Hablo con todo el público.', ru: 'Разговариваю со всеми зрителями.' },
    ],
    correctAnswer: 'B',
    explanationRu: 'В кинотеатре вопросы лучше обсуждать уже после сеанса («después de la película»), не прерывая просмотр.',
    prizeMoney: 10000,
  },
  {
    id: 7,
    category: 'cine',
    categoryTitleEs: '🎬 Cine',
    categoryTitleRu: 'Кинотеатр',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has perdido (ты потерял) — от глагола perder (Pretérito Perfecto).',
    questionEs: 'Has perdido tu entrada antes de entrar. ¿Qué haces?',
    questionRu: 'Ты потерял билет перед входом. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Entro sin decir nada.', ru: 'Захожу, ничего не говоря.' },
      { id: 'B', es: 'Hablo con la taquilla y explico el problema.', ru: 'Иду в кассу и объясняю проблему.' },
      { id: 'C', es: 'Uso la entrada de otra persona.', ru: 'Использую чужой билет.' },
      { id: 'D', es: 'Me escondo.', ru: 'Прячусь.' },
    ],
    correctAnswer: 'B',
    explanationRu: '«La taquilla» — это билетная касса. Там помогут восстановить электронный или распечатанный билет.',
    prizeMoney: 15000,
  },
  {
    id: 8,
    category: 'cine',
    categoryTitleEs: '🎬 Cine',
    categoryTitleRu: 'Кинотеатр',
    tense: 'Presente',
    tenseExplanationRu: 'Quieres (ты хочешь, querer e -> ie) / están agotadas (закончились/распроданы) — Presente.',
    questionEs: 'Quieres ver una película, pero todas las entradas están agotadas. ¿Qué haces?',
    questionRu: 'Ты хочешь посмотреть фильм, но все билеты распроданы. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Entro sin entrada.', ru: 'Захожу без билета.' },
      { id: 'B', es: 'Busco otra sesión.', ru: 'Ищу другой сеанс.' },
      { id: 'C', es: 'Discuto con el empleado.', ru: 'Спорю с сотрудником.' },
      { id: 'D', es: 'Ocupo el asiento de alguien.', ru: 'Занимаю чьё-то место.' },
    ],
    correctAnswer: 'B',
    explanationRu: '«Otra sesión» означает другой сеанс (по времени или в другой день).',
    prizeMoney: 25000,
  },
  {
    id: 9,
    category: 'cine',
    categoryTitleEs: '🎬 Cine',
    categoryTitleRu: 'Кинотеатр',
    tense: 'Presente',
    tenseExplanationRu: 'Habla (разговаривает) / pido (прошу, глагол pedir e -> i) — Presente.',
    questionEs: 'Tu amigo habla durante toda la película. ¿Qué haces?',
    questionRu: 'Твой друг разговаривает весь фильм. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Le pido que hable más bajo.', ru: 'Прошу его говорить тише.' },
      { id: 'B', es: 'Empiezo a gritar.', ru: 'Начинаю кричать.' },
      { id: 'C', es: 'Hablo todavía más fuerte.', ru: 'Говорю ещё громче.' },
      { id: 'D', es: 'Lanzo palomitas.', ru: 'Бросаю попкорн.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Hablar más bajo» — говорить тише. Вежливая и эффективная просьба.',
    prizeMoney: 50000,
  },
  {
    id: 10,
    category: 'cine',
    categoryTitleEs: '🎬 Cine',
    categoryTitleRu: 'Кинотеатр',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Ha terminado (закончился) — Pretérito Perfecto от terminar.',
    questionEs: 'La película ha terminado. ¿Qué haces antes de salir?',
    questionRu: 'Фильм закончился. Что ты делаешь перед выходом?',
    options: [
      { id: 'A', es: 'Dejo toda la basura en el asiento.', ru: 'Оставляю весь мусор на сиденье.' },
      { id: 'B', es: 'Recojo mis cosas y tiro la basura.', ru: 'Собираю свои вещи и выбрасываю мусор.' },
      { id: 'C', es: 'Me llevo algo que no es mío.', ru: 'Забираю что-то чужое.' },
      { id: 'D', es: 'Entro en otra sala sin entrada.', ru: 'Захожу в другой зал без билета.' },
    ],
    correctAnswer: 'B',
    explanationRu: '«Recoger las cosas» — забрать свои вещи, «tirar la basura» — выбросить мусор в урну у выхода.',
    prizeMoney: 100000,
  },

  // --- 👕 Tienda — Магазин (11 - 20) ---
  {
    id: 11,
    category: 'tienda',
    categoryTitleEs: '👕 Tienda',
    categoryTitleRu: 'Магазин',
    tense: 'Presente',
    tenseExplanationRu: 'Te gusta (тебе нравится) / sabes (знаешь) / cuesta (стоит) — Presente.',
    questionEs: 'Te gusta una camiseta, pero no sabes cuánto cuesta. ¿Qué haces?',
    questionRu: 'Тебе нравится футболка, но ты не знаешь цену. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Pregunto el precio.', ru: 'Спрашиваю цену.' },
      { id: 'B', es: 'Me la llevo sin pagar.', ru: 'Забираю её не заплатив.' },
      { id: 'C', es: 'La escondo.', ru: 'Прячу её.' },
      { id: 'D', es: 'Invento el precio.', ru: 'Придумываю цену.' },
    ],
    correctAnswer: 'A',
    explanationRu: 'Фраза: «¿Cuánto cuesta?» (Сколько стоит?) — базовый вопрос в любом магазине Испании.',
    prizeMoney: 150000,
  },
  {
    id: 12,
    category: 'tienda',
    categoryTitleEs: '👕 Tienda',
    categoryTitleRu: 'Магазин',
    tense: 'Presente',
    tenseExplanationRu: 'Quieres (хочешь) / te queda (сидит на тебе) / voy (иду) — Presente.',
    questionEs: 'Quieres saber cómo te queda un pantalón antes de comprarlo. ¿Qué haces?',
    questionRu: 'Ты хочешь узнать, как сидят брюки, перед покупкой. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Voy al probador.', ru: 'Иду в примерочную.' },
      { id: 'B', es: 'Me lo pongo en la calle.', ru: 'Надеваю их прямо на улице.' },
      { id: 'C', es: 'Corto la tela con tijeras.', ru: 'Режу ткань ножницами.' },
      { id: 'D', es: 'Me voy enfadado.', ru: 'Ухожу рассерженным.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«El probador» — примерочная кабина. От глагола probar (примерять).',
    prizeMoney: 250000,
  },
  {
    id: 13,
    category: 'tienda',
    categoryTitleEs: '👕 Tienda',
    categoryTitleRu: 'Магазин',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has probado (ты примерил) — Pretérito Perfecto.',
    questionEs: 'Has probado una chaqueta y te queda pequeña. ¿Qué haces?',
    questionRu: 'Ты примерил куртку, и она тебе мала. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Pido una talla más grande.', ru: 'Прошу размер побольше.' },
      { id: 'B', es: 'La rompo.', ru: 'Рву её.' },
      { id: 'C', es: 'Compro dos iguales.', ru: 'Покупаю две одинаковые.' },
      { id: 'D', es: 'Digo que me queda perfecta.', ru: 'Говорю, что она сидит идеально.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Una talla más grande» — размер побольше, «una talla más pequeña» — размер поменьше.',
    prizeMoney: 400000,
  },
  {
    id: 14,
    category: 'tienda',
    categoryTitleEs: '👕 Tienda',
    categoryTitleRu: 'Магазин',
    tense: 'Presente',
    tenseExplanationRu: 'Te gusta (нравится) / está (находится) / tiene (имеет) — Presente.',
    questionEs: 'Te gusta una camisa pero no ves la tuya en el perchero. ¿Qué preguntas?',
    questionRu: 'Тебе нравится рубашка, но своего размера на вешалке ты не видишь. Что ты спрашиваешь?',
    options: [
      { id: 'A', es: '¿Tiene otra talla?', ru: 'У вас есть другой размер?' },
      { id: 'B', es: '¿Tiene entradas de cine?', ru: 'У вас есть билеты в кино?' },
      { id: 'C', es: '¿Dónde está el museo?', ru: 'Где находится музей?' },
      { id: 'D', es: '¿Vende pescado fresco?', ru: 'Вы продаёте свежую рыбу?' },
    ],
    correctAnswer: 'A',
    explanationRu: 'Вопрос «¿Tiene otra talla?» или «¿Tiene la talla M / L?» используется постоянно при покупках одежды.',
    prizeMoney: 600000,
  },
  {
    id: 15,
    category: 'tienda',
    categoryTitleEs: '👕 Tienda',
    categoryTitleRu: 'Магазин',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has comprado (ты купил) / vuelvo (возвращаюсь) — Pretérito Perfecto и Presente.',
    questionEs: 'Has comprado un jersey y en casa ves que tiene un defecto. ¿Qué haces?',
    questionRu: 'Ты купил свитер, а дома заметил, что у него дефект. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Vuelvo a la tienda con el ticket.', ru: 'Возвращаюсь в магазин с чеком.' },
      { id: 'B', es: 'Tiro el jersey por la ventana.', ru: 'Выбрасываю свитер в окно.' },
      { id: 'C', es: 'No vuelvo a vestirme nunca.', ru: 'Никогда больше не одеваюсь.' },
      { id: 'D', es: 'Culpo a mis vecinos.', ru: 'Виню своих соседей.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«El ticket de compra» — чек из магазина. Без чека оформить возврат (devolución) или обмен очень сложно.',
    prizeMoney: 1000000,
  },
  {
    id: 16,
    category: 'tienda',
    categoryTitleEs: '👕 Tienda',
    categoryTitleRu: 'Магазин',
    tense: 'Presente',
    tenseExplanationRu: 'Pregunta (спрашивает) / necesitas (нуждаешься) / respondes (отвечаешь) — Presente.',
    questionEs: 'El dependiente te pregunta: «¿Puedo ayudarte?». No necesitas ayuda. ¿Qué respondes?',
    questionRu: 'Продавец спрашивает: «Могу помочь?». Помощь тебе не нужна. Что ты отвечаешь?',
    options: [
      { id: 'A', es: 'No, gracias. Solo estoy mirando.', ru: 'Нет, спасибо. Я просто смотрю.' },
      { id: 'B', es: 'No hablo español.', ru: 'Я не говорю по-испански.' },
      { id: 'C', es: 'Dame dinero.', ru: 'Дай мне денег.' },
      { id: 'D', es: 'Cierra la tienda.', ru: 'Закрой магазин.' },
    ],
    correctAnswer: 'A',
    explanationRu: 'Классическая испанская вежливая реплика покупателя: «Solo estoy mirando, gracias» (Я просто смотрю, спасибо).',
    prizeMoney: 500,
  },
  {
    id: 17,
    category: 'tienda',
    categoryTitleEs: '👕 Tienda',
    categoryTitleRu: 'Магазин',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has visto (ты увидел) — Pretérito Perfecto от ver (неправильное причастие: visto).',
    questionEs: 'Has visto una chaqueta de cuero pero supera tu presupuesto. ¿Qué haces?',
    questionRu: 'Ты увидел кожаную куртку, но она превышает твой бюджет. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Busco otra más barata.', ru: 'Ищу другую, подешевле.' },
      { id: 'B', es: 'Pido que me la regalen gratis.', ru: 'Прошу подарить её мне бесплатно.' },
      { id: 'C', es: 'Corro con la chaqueta a la calle.', ru: 'Бегу с курткой на улицу.' },
      { id: 'D', es: 'Escondo la chaqueta bajo la alfombra.', ru: 'Прячу куртку под коврик.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Más barata» — более дешёвая, от «barato» (дешёвый). «Caro» — дорогой.',
    prizeMoney: 1000,
  },
  {
    id: 18,
    category: 'tienda',
    categoryTitleEs: '👕 Tienda',
    categoryTitleRu: 'Магазин',
    tense: 'Presente',
    tenseExplanationRu: 'Quieres (хочешь) / preguntas (спрашиваешь) / puedo (могу) — Presente.',
    questionEs: 'Quieres pagar con tarjeta. ¿Qué preguntas?',
    questionRu: 'Ты хочешь заплатить картой. Что ты спрашиваешь?',
    options: [
      { id: 'A', es: '¿Puedo pagar con tarjeta?', ru: 'Могу я оплатить картой?' },
      { id: 'B', es: '¿Puedo dormir aquí?', ru: 'Могу я поспать здесь?' },
      { id: 'C', es: '¿Puedo jugar al fútbol?', ru: 'Могу я сыграть в футбол?' },
      { id: 'D', es: '¿Puedo abrir la ventana?', ru: 'Могу я открыть окно?' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Pagar con tarjeta» — платить картой, «en efectivo» — наличными.',
    prizeMoney: 2000,
  },
  {
    id: 19,
    category: 'tienda',
    categoryTitleEs: '👕 Tienda',
    categoryTitleRu: 'Магазин',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has mirado (ты посмотрел) / han cobrado (тебе пробили/взяли оплату) — Pretérito Perfecto.',
    questionEs: 'Has mirado el ticket y ves que te han cobrado dos veces el mismo artículo. ¿Qué haces?',
    questionRu: 'Ты посмотрел чек и видишь, что тебе дважды пробили один и тот же товар. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Lo compruebo y se lo digo educadamente.', ru: 'Проверяю это и вежливо говорю об этом продавцу.' },
      { id: 'B', es: 'Me pongo a gritar y rompo la puerta.', ru: 'Начинаю кричать и ломаю дверь.' },
      { id: 'C', es: 'No digo nada y pago el doble con gusto.', ru: 'Ничего не говорю и с удовольствием плачу вдвое.' },
      { id: 'D', es: 'Me voy corriendo de la ciudad.', ru: 'Убегаю из города.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Comprobar» — проверить, «educadamente» — вежливо. Всегда стоит спокойно показать чек кассиру.',
    prizeMoney: 3000,
  },
  {
    id: 20,
    category: 'tienda',
    categoryTitleEs: '👕 Tienda',
    categoryTitleRu: 'Магазин',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has comprado (ты купил) — Pretérito Perfecto.',
    questionEs: 'Has comprado un regalo para tu amigo. ¿Qué puedes pedir?',
    questionRu: 'Ты купил подарок другу. Что можно попросить?',
    options: [
      { id: 'A', es: '¿Puede envolverlo para regalo?', ru: 'Можете завернуть как подарок?' },
      { id: 'B', es: '¿Puede comérselo?', ru: 'Можете съесть его?' },
      { id: 'C', es: '¿Puede jugar con él?', ru: 'Можете поиграть с ним?' },
      { id: 'D', es: '¿Puede devolverme dos regalos?', ru: 'Можете вернуть мне два подарка?' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Envolver para regalo» — упаковать в подарочную бумагу. Часто в магазинах Испании это делают бесплатно.',
    prizeMoney: 5000,
  },

  // --- 🛣️ En la calle / Camino — Дорога (21 - 32) ---
  {
    id: 21,
    category: 'camino',
    categoryTitleEs: '🛣️ Camino',
    categoryTitleRu: 'Дорога / Улица',
    tense: 'Presente',
    tenseExplanationRu: 'No sabes (ты не знаешь) / llegar (добраться) / preguntas (спрашиваешь) — Presente.',
    questionEs: 'No sabes cómo llegar a la estación. ¿Qué haces?',
    questionRu: 'Ты не знаешь, как дойти до станции. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Pregunto cómo llegar.', ru: 'Спрашиваю, как добраться.' },
      { id: 'B', es: 'Camino sin mirar durante horas.', ru: 'Иду не глядя часами.' },
      { id: 'C', es: 'Entro en cualquier casa.', ru: 'Захожу в любой дом.' },
      { id: 'D', es: 'Espero que alguien adivine mi problema.', ru: 'Жду, что кто-то угадает мою проблему.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«¿Cómo llego a la estación?» или «¿Por dónde se va a la estación?» — самые естественные фразы в Испании.',
    prizeMoney: 10000,
  },
  {
    id: 22,
    category: 'camino',
    categoryTitleEs: '🛣️ Camino',
    categoryTitleRu: 'Дорога / Улица',
    tense: 'Presente',
    tenseExplanationRu: 'Quieres (хочешь) / cruzar (перейти) / busco (ищу) — Presente.',
    questionEs: 'Quieres cruzar una calle con mucho tráfico. ¿Qué haces?',
    questionRu: 'Ты хочешь перейти улицу с сильным движением. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Busco un paso de peatones.', ru: 'Ищу пешеходный переход.' },
      { id: 'B', es: 'Corro entre los coches.', ru: 'Бегу между машинами.' },
      { id: 'C', es: 'Cierro los ojos y cruzo.', ru: 'Закрываю глаза и перехожу.' },
      { id: 'D', es: 'Camino por medio de la carretera.', ru: 'Иду прямо посередине дороги.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«El paso de peatones» — пешеходный переход (зебра). Безопасный способ перейти дорогу.',
    prizeMoney: 15000,
  },
  {
    id: 23,
    category: 'camino',
    categoryTitleEs: '🛣️ Camino',
    categoryTitleRu: 'Дорога / Улица',
    tense: 'Presente',
    tenseExplanationRu: 'Está (находится / горит красным) / espero (жду) — Presente.',
    questionEs: 'El semáforo para peatones está en rojo. ¿Qué haces?',
    questionRu: 'Светофор для пешеходов красный. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Espero.', ru: 'Жду.' },
      { id: 'B', es: 'Cruzo rápidamente.', ru: 'Быстро перехожу.' },
      { id: 'C', es: 'Corro.', ru: 'Бегу.' },
      { id: 'D', es: 'Ignoro el semáforo.', ru: 'Игнорирую светофор.' },
    ],
    correctAnswer: 'A',
    explanationRu: 'Красный свет — «el semáforo en rojo». Нужно ждать зелёного («esperar a que esté en verde»).',
    prizeMoney: 25000,
  },
  {
    id: 24,
    category: 'camino',
    categoryTitleEs: '🛣️ Camino',
    categoryTitleRu: 'Дорога / Улица',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Te has perdido (ты заблудился) — Pretérito Perfecto возвратного глагола perderse.',
    questionEs: 'Te has perdido en una ciudad que no conoces. ¿Qué haces?',
    questionRu: 'Ты заблудился в незнакомом городе. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Miro el mapa o pregunto a alguien.', ru: 'Смотрю карту или спрашиваю у кого-нибудь.' },
      { id: 'B', es: 'Sigo caminando sin dirección.', ru: 'Продолжаю идти без направления.' },
      { id: 'C', es: 'Me enfado con todos.', ru: 'Злюсь на всех.' },
      { id: 'D', es: 'Entro en cualquier autobús.', ru: 'Сажусь в любой автобус.' },
    ],
    correctAnswer: 'A',
    explanationRu: 'Посмотреть карту («el mapa») или вежливо спросить прохожего («preguntar a alguien») — лучший способ сориентироваться.',
    prizeMoney: 50000,
  },
  {
    id: 25,
    category: 'camino',
    categoryTitleEs: '🛣️ Camino',
    categoryTitleRu: 'Дорога / Улица',
    tense: 'Presente',
    tenseExplanationRu: 'Pregunta (спрашивает) / conoces (знаешь) / explico (объясняю) — Presente.',
    questionEs: 'Una persona te pregunta cómo llegar al museo y conoces el camino. ¿Qué haces?',
    questionRu: 'Человек спрашивает, как пройти к музею, и ты знаешь дорогу. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Le explico el camino.', ru: 'Объясняю ему дорогу.' },
      { id: 'B', es: 'Le doy información falsa.', ru: 'Даю ему ложную информацию.' },
      { id: 'C', es: 'No digo nada.', ru: 'Ничего не говорю.' },
      { id: 'D', es: 'Le digo que vaya a otro país.', ru: 'Говорю ему ехать в другую страну.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Explicar el camino» — объяснить маршрут, например: «Todo recto y a la derecha» (Прямо и направо).',
    prizeMoney: 100000,
  },
  {
    id: 26,
    category: 'camino',
    categoryTitleEs: '🛣️ Camino',
    categoryTitleRu: 'Дорога / Улица',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has tomado (ты сел/взял) — Pretérito Perfecto от tomar.',
    questionEs: 'Has tomado el autobús equivocado. ¿Qué haces?',
    questionRu: 'Ты сел не на тот автобус. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Pregunto dónde puedo bajar y cambiar de autobús.', ru: 'Спрашиваю, где сойти и пересесть на другой автобус.' },
      { id: 'B', es: 'Culpo al conductor.', ru: 'Виню водителя.' },
      { id: 'C', es: 'Me escondo.', ru: 'Прячусь.' },
      { id: 'D', es: 'Continúo hasta el final sin preguntar.', ru: 'Еду до конца, ничего не спрашивая.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Bajar» — сойти (с автобуса/поезда), «cambiar de autobús» — сделать пересадку.',
    prizeMoney: 150000,
  },
  {
    id: 27,
    category: 'camino',
    categoryTitleEs: '🛣️ Camino',
    categoryTitleRu: 'Дорога / Улица',
    tense: 'Presente',
    tenseExplanationRu: 'No sabes (ты не знаешь) / está (находится) / preguntas (спрашиваешь) — Presente.',
    questionEs: 'No sabes dónde está la parada de autobús. ¿Qué preguntas?',
    questionRu: 'Ты не знаешь, где автобусная остановка. Что ты спрашиваешь?',
    options: [
      { id: 'A', es: '¿Dónde está la parada de autobús?', ru: 'Где находится автобусная остановка?' },
      { id: 'B', es: '¿Cuánto cuesta esta camiseta?', ru: 'Сколько стоит эта футболка?' },
      { id: 'C', es: '¿Qué película ponen?', ru: 'Какой фильм показывают?' },
      { id: 'D', es: '¿Tiene leche?', ru: 'У вас есть молоко?' },
    ],
    correctAnswer: 'A',
    explanationRu: '«La parada de autobús» — автобусная остановка. «¿Dónde está...?» — ключевой вопрос для поиска мест.',
    prizeMoney: 250000,
  },
  {
    id: 28,
    category: 'camino',
    categoryTitleEs: '🛣️ Camino',
    categoryTitleRu: 'Дорога / Улица',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has olvidado (ты забыл) / has aparcado (припарковал) — Pretérito Perfecto.',
    questionEs: 'Has olvidado dónde has aparcado la bicicleta. ¿Qué haces?',
    questionRu: 'Ты забыл, где оставил велосипед. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Intento recordar el lugar y lo busco.', ru: 'Пытаюсь вспомнить место и ищу его.' },
      { id: 'B', es: 'Cojo otra bicicleta.', ru: 'Беру чужой велосипед.' },
      { id: 'C', es: 'Digo que todas son mías.', ru: 'Говорю, что все велосипеды мои.' },
      { id: 'D', es: 'Me voy corriendo.', ru: 'Убегаю прочь.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Recordar el lugar» — вспомнить место, «buscar» — искать.',
    prizeMoney: 400000,
  },
  {
    id: 29,
    category: 'camino',
    categoryTitleEs: '🛣️ Camino',
    categoryTitleRu: 'Дорога / Улица',
    tense: 'Presente',
    tenseExplanationRu: 'Ves (видишь, глагол ver) / tiene (имеет) / ofrezco (предлагаю) — Presente.',
    questionEs: 'Ves a una persona mayor que tiene dificultad para cruzar. ¿Qué haces?',
    questionRu: 'Ты видишь пожилого человека, которому трудно перейти дорогу. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Le ofrezco ayuda si la necesita.', ru: 'Предлагаю ему помощь, если она нужна.' },
      { id: 'B', es: 'Paso corriendo a su lado.', ru: 'Пробегаю мимо него.' },
      { id: 'C', es: 'Me río.', ru: 'Смеюсь.' },
      { id: 'D', es: 'Le digo que espere una hora.', ru: 'Говорю ему подождать час.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Ofrecer ayuda» — предложить помощь: «¿Le ayudo a cruzar?» (Помочь вам перейти?).',
    prizeMoney: 600000,
  },
  {
    id: 30,
    category: 'camino',
    categoryTitleEs: '🛣️ Camino',
    categoryTitleRu: 'Дорога / Улица',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has llegado (ты дошёл/прибыл) — Pretérito Perfecto от llegar.',
    questionEs: 'Has llegado a una calle cerrada por obras. ¿Qué haces?',
    questionRu: 'Ты дошёл до улицы, перекрытой из-за ремонта. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Busco otra ruta.', ru: 'Ищу другой маршрут.' },
      { id: 'B', es: 'Paso por la zona prohibida.', ru: 'Иду через запретную зону.' },
      { id: 'C', es: 'Quito las señales.', ru: 'Убираю дорожные знаки.' },
      { id: 'D', es: 'Entro entre las máquinas.', ru: 'Захожу прямо между машинами.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Obras» — ремонтные или дорожные работы. При перекрытии ищут объездной путь («otra ruta»).',
    prizeMoney: 1000000,
  },
  {
    id: 31,
    category: 'camino',
    categoryTitleEs: '🛣️ Camino',
    categoryTitleRu: 'Дорога / Улица',
    tense: 'Presente',
    tenseExplanationRu: 'Vas (идёшь, глагол ir) / empieza a llover (начинается дождь) / busco (ищу) — Presente.',
    questionEs: 'Vas andando y empieza a llover mucho. ¿Qué haces?',
    questionRu: 'Ты идёшь по улице, и начинается сильный дождь. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Busco un lugar cubierto o uso un paraguas.', ru: 'Ищу укрытие или открываю зонт.' },
      { id: 'B', es: 'Me siento en medio de la calle.', ru: 'Сажусь посреди улицы.' },
      { id: 'C', es: 'Tiro mis cosas.', ru: 'Выбрасываю свои вещи.' },
      { id: 'D', es: 'Camino dentro de un charco.', ru: 'Иду прямо по луже.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Un paraguas» — зонт, «un lugar cubierto» — укрытие под навесом или крышей.',
    prizeMoney: 500,
  },
  {
    id: 32,
    category: 'camino',
    categoryTitleEs: '🛣️ Camino',
    categoryTitleRu: 'Дорога / Улица',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has encontrado (ты нашёл) — Pretérito Perfecto от encontrar.',
    questionEs: 'Has encontrado una cartera en la calle. ¿Qué haces?',
    questionRu: 'Ты нашёл кошелёк на улице. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Intento entregarlo a la policía o encontrar a su dueño.', ru: 'Пытаюсь отдать его в полицию или найти владельца.' },
      { id: 'B', es: 'Me quedo con todo.', ru: 'Забираю всё себе.' },
      { id: 'C', es: 'Lo tiro.', ru: 'Выбрасываю его.' },
      { id: 'D', es: 'Escondo la cartera.', ru: 'Прячу кошелёк.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«La cartera» — кошелёк, «el dueño» — владелец. Честный поступок — обратиться в полицию (oficina de objetos perdidos).',
    prizeMoney: 1000,
  },

  // --- 🛒 Supermercado — Супермаркет (33 - 50) ---
  {
    id: 33,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Presente',
    tenseExplanationRu: 'Necesitas (нуждаешься) / sabes (знаешь) / pregunto (спрашиваю) — Presente.',
    questionEs: 'Necesitas leche, pero no sabes dónde está. ¿Qué haces?',
    questionRu: 'Тебе нужно молоко, но ты не знаешь, где оно находится. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Pregunto a un empleado.', ru: 'Спрашиваю у сотрудника магазина.' },
      { id: 'B', es: 'Abro todas las cajas.', ru: 'Вскрываю все коробки.' },
      { id: 'C', es: 'Me voy sin buscar.', ru: 'Ухожу не поискав.' },
      { id: 'D', es: 'Pregunto por el cine.', ru: 'Спрашиваю про кинотеатр.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«¿Dónde está la leche, por favor?» — сотрудник супермаркета сразу подскажет нужный проход (pasillo).',
    prizeMoney: 2000,
  },
  {
    id: 34,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has visto (ты увидел) / dejo y aviso (оставляю и предупреждаю) — Pretérito Perfecto и Presente.',
    questionEs: 'Has visto una botella rota de aceite en el pasillo. ¿Qué haces?',
    questionRu: 'Ты увидел разбитую бутылку масла в проходе. Что ты делаешь?',
    options: [
      { id: 'A', es: 'La dejo y aviso a un empleado.', ru: 'Оставляю её на месте и предупреждаю сотрудника.' },
      { id: 'B', es: 'Camino por encima del aceite.', ru: 'Иду прямо по маслу.' },
      { id: 'C', es: 'Intento beberlo del suelo.', ru: 'Пытаюсь выпить масло с пола.' },
      { id: 'D', es: 'Escondo los cristales en mi bolsillo.', ru: 'Прячу осколки стекла в карман.' },
    ],
    correctAnswer: 'A',
    explanationRu: 'Осколки и масло опасны: нужно позвать персонал магазина, чтобы никто не поскользнулся.',
    prizeMoney: 3000,
  },
  {
    id: 35,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Presente',
    tenseExplanationRu: 'Quieres (хочешь) / comprar (купить) / peso (взвешиваю) — Presente.',
    questionEs: 'Quieres comprar un kilo de manzanas. ¿Qué haces?',
    questionRu: 'Ты хочешь купить килограмм яблок. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Peso las manzanas.', ru: 'Взвешиваю яблоки на весах.' },
      { id: 'B', es: 'Compro diez litros.', ru: 'Покупаю десять литров.' },
      { id: 'C', es: 'Busco zapatos.', ru: 'Ищу обувь.' },
      { id: 'D', es: 'Voy al cine.', ru: 'Иду в кино.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Pesar la fruta» — взвесить фрукты. В испанских супермаркетах часто взвешивают в отделе фруктов и наклеивают ценник.',
    prizeMoney: 5000,
  },
  {
    id: 36,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Presente',
    tenseExplanationRu: 'Tienes (у тебя есть, tener) / cuesta (стоит) / recibes (получаешь) — Presente.',
    questionEs: 'Tienes 10 euros y tu compra cuesta 8 euros. ¿Cuánto cambio recibes?',
    questionRu: 'У тебя 10 евро, покупка стоит 8 евро. Сколько сдачи ты получаешь?',
    options: [
      { id: 'A', es: '1 euro.', ru: '1 евро.' },
      { id: 'B', es: '2 euros.', ru: '2 евро.' },
      { id: 'C', es: '8 euros.', ru: '8 евро.' },
      { id: 'D', es: '18 euros.', ru: '18 евро.' },
    ],
    correctAnswer: 'B',
    explanationRu: '10 − 8 = 2 евро. «El cambio» или «la vuelta» — это сдача при покупке.',
    prizeMoney: 10000,
  },
  {
    id: 37,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has olvidado (ты забыл) — Pretérito Perfecto от olvidar.',
    questionEs: 'Has olvidado la lista de la compra en casa. ¿Qué haces?',
    questionRu: 'Ты забыл список покупок дома. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Intento recordar lo necesario o miro una foto si la tengo.', ru: 'Пытаюсь вспомнить нужное или смотрю фото, если оно есть.' },
      { id: 'B', es: 'Compro todo el supermercado.', ru: 'Скупаю весь супермаркет.' },
      { id: 'C', es: 'No compro nada nunca.', ru: 'Никогда ничего не покупаю.' },
      { id: 'D', es: 'Pregunto a otro cliente qué necesito yo.', ru: 'Спрашиваю другого покупателя, что нужно мне.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«La lista de la compra» — список покупок. Вспомнить самое необходимое — практичный выход.',
    prizeMoney: 15000,
  },
  {
    id: 38,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Presente + Pretérito Perfecto',
    tenseExplanationRu: 'Ves (видишь — Presente), ha caducado (истёк срок — Pretérito Perfecto).',
    questionEs: 'Ves que un producto ha caducado. ¿Qué haces?',
    questionRu: 'Ты замечаешь, что срок годности продукта истёк. Что ты делаешь?',
    options: [
      { id: 'A', es: 'No lo compro y puedo avisar a un empleado.', ru: 'Не покупаю его и могу предупредить сотрудника.' },
      { id: 'B', es: 'Lo compro porque está viejo.', ru: 'Покупаю его, потому что он старый.' },
      { id: 'C', es: 'Borro la fecha con el dedo.', ru: 'Стираю дату пальцем.' },
      { id: 'D', es: 'Lo abro y lo dejo allí.', ru: 'Вскрываю упаковку и бросаю там.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Fecha de caducidad» — срок годности. Просроченный товар не берут и сообщают мерчандайзеру.',
    prizeMoney: 25000,
  },
  {
    id: 39,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Presente',
    tenseExplanationRu: 'Hay (имеется/есть) / espero (жду) — Presente.',
    questionEs: 'Hay una cola larga en la caja. ¿Qué haces?',
    questionRu: 'У кассы длинная очередь. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Espero mi turno.', ru: 'Жду своей очереди.' },
      { id: 'B', es: 'Paso delante de todos.', ru: 'Пролезаю перед всеми.' },
      { id: 'C', es: 'Empujo a la gente.', ru: 'Толкаю людей.' },
      { id: 'D', es: 'Dejo el carro en medio.', ru: 'Бросаю тележку посредине.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Hacer cola» — стоять в очереди, «el turno» — очередь. В Испании уважение очереди очень важно.',
    prizeMoney: 50000,
  },
  {
    id: 40,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has comprado (ты купил) / falta (не хватает) — Pretérito Perfecto и Presente.',
    questionEs: 'Has comprado un pack de cuatro yogures pero al abrirlo solo ves tres. ¿Qué ocurre?',
    questionRu: 'Ты купил упаковку из 4 йогуртов, а открыв, видишь только 3. Что происходит?',
    options: [
      { id: 'A', es: 'Falta un yogur.', ru: 'Не хватает одного йогурта.' },
      { id: 'B', es: 'Hay demasiados yogures.', ru: 'Йогуртов слишком много.' },
      { id: 'C', es: 'Tengo diez yogures.', ru: 'У меня десять йогуртов.' },
      { id: 'D', es: 'Todo está completo.', ru: 'Всё в полном комплекте.' },
    ],
    correctAnswer: 'A',
    explanationRu: 'Глагол «faltar» выражает нехватку: «Falta un yogur» (Одного йогурта не хватает).',
    prizeMoney: 100000,
  },
  {
    id: 41,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Presente',
    tenseExplanationRu: 'Quieres (хочешь) / contiene (содержит) / leo (читаю) — Presente.',
    questionEs: 'Quieres saber si un producto contiene gluten o frutos secos. ¿Qué haces?',
    questionRu: 'Ты хочешь узнать, содержит ли продукт глютен или орехи. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Leo la etiqueta.', ru: 'Читаю этикетку (состав).' },
      { id: 'B', es: 'Como todo sin mirar.', ru: 'Ем всё не глядя.' },
      { id: 'C', es: 'Tiro el paquete al techo.', ru: 'Подбрасываю пачку к потолку.' },
      { id: 'D', es: 'Pregunto por el director de cine.', ru: 'Спрашиваю про кинорежиссёра.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«La etiqueta» — этикетка с составом и списком аллергенов («alérgenos»).',
    prizeMoney: 150000,
  },
  {
    id: 42,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has puesto (ты положил, poner — нерегулярное puesto) / cuestan (стоят) — Pretérito Perfecto и Presente.',
    questionEs: 'Has puesto dos panes de 2 euros cada uno en el carrito. ¿Cuánto cuestan?',
    questionRu: 'Ты положил в тележку два хлеба по 2 евро каждый. Сколько они стоят?',
    options: [
      { id: 'A', es: '2 euros.', ru: '2 евро.' },
      { id: 'B', es: '3 euros.', ru: '3 евро.' },
      { id: 'C', es: '4 euros.', ru: '4 евро.' },
      { id: 'D', es: '6 euros.', ru: '6 евро.' },
    ],
    correctAnswer: 'C',
    explanationRu: '2 хлеба × 2 евро = 4 евро («cuatro euros»). «Cada uno» означает «каждый».',
    prizeMoney: 250000,
  },
  {
    id: 43,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Presente',
    tenseExplanationRu: 'Quieres (хочешь) / tienes (имеешь) / faltan (не хватает) — Presente.',
    questionEs: 'Quieres comprar diez botellas de agua pero solo tienes seis en el carro. ¿Están todas?',
    questionRu: 'Ты хочешь купить 10 бутылок воды, но в тележке только 6. Все ли на месте?',
    options: [
      { id: 'A', es: 'Sí, son diez.', ru: 'Да, их десять.' },
      { id: 'B', es: 'No, faltan cuatro.', ru: 'Нет, не хватает четырёх.' },
      { id: 'C', es: 'Hay demasiadas botellas.', ru: 'Бутылок слишком много.' },
      { id: 'D', es: 'Tienes veinte botellas.', ru: 'У тебя двадцать бутылок.' },
    ],
    correctAnswer: 'B',
    explanationRu: '10 − 6 = 4. «Faltan cuatro» — не хватает четырёх штук.',
    prizeMoney: 400000,
  },
  {
    id: 44,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Presente + Pretérito Perfecto',
    tenseExplanationRu: 'Has terminado (ты закончил — Pretérito Perfecto), vas (идёшь — Presente от ir).',
    questionEs: 'Has terminado de comprar y quieres pagar. ¿Dónde vas?',
    questionRu: 'Ты закончил покупки и хочешь заплатить. Куда ты идёшь?',
    options: [
      { id: 'A', es: 'A la caja.', ru: 'К кассе.' },
      { id: 'B', es: 'Al cine.', ru: 'В кино.' },
      { id: 'C', es: 'Al probador.', ru: 'В примерочную.' },
      { id: 'D', es: 'A la parada.', ru: 'На остановку.' },
    ],
    correctAnswer: 'A',
    explanationRu: 'Оплата покупок происходит на кассе («la caja del supermercado»).',
    prizeMoney: 600000,
  },
  {
    id: 45,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has pagado (ты заплатил) / ha costado (стоила) — Pretérito Perfecto.',
    questionEs: 'Has pagado con 20 euros y la compra ha costado 15. ¿Cuánto te tienen que devolver?',
    questionRu: 'Ты заплатил 20 евро, а покупка стоила 15. Сколько тебе должны вернуть?',
    options: [
      { id: 'A', es: '3 euros.', ru: '3 евро.' },
      { id: 'B', es: '5 euros.', ru: '5 евро.' },
      { id: 'C', es: '15 euros.', ru: '15 евро.' },
      { id: 'D', es: '35 euros.', ru: '35 евро.' },
    ],
    correctAnswer: 'B',
    explanationRu: '20 − 15 = 5 евро («cinco euros de cambio»). «Devolver» — вернуть сдачу.',
    prizeMoney: 1000000,
  },
  {
    id: 46,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Presente',
    tenseExplanationRu: 'Cuesta (стоит) / compras (покупаешь) / pagas (платишь) — Presente.',
    questionEs: 'Un producto cuesta 3 euros y compras tres. ¿Cuánto pagas?',
    questionRu: 'Один продукт стоит 3 евро, ты покупаешь три. Сколько ты платишь?',
    options: [
      { id: 'A', es: '6 euros.', ru: '6 евро.' },
      { id: 'B', es: '9 euros.', ru: '9 евро.' },
      { id: 'C', es: '3 euros.', ru: '3 евро.' },
      { id: 'D', es: '12 euros.', ru: '12 евро.' },
    ],
    correctAnswer: 'B',
    explanationRu: '3 × 3 = 9 евро («nueve euros en total»).',
    prizeMoney: 500,
  },
  {
    id: 47,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has llegado (ты пришёл) / te das cuenta (понимаешь/осознаёшь) / has olvidado (забыл) — Pretérito Perfecto и Presente.',
    questionEs: 'Has llegado a casa y te das cuenta de que has olvidado comprar pan. ¿Qué haces?',
    questionRu: 'Ты пришёл домой и понял, что забыл купить хлеб. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Si lo necesito, vuelvo a comprarlo.', ru: 'Если он мне нужен, возвращаюсь и докупаю.' },
      { id: 'B', es: 'Digo que nunca más como.', ru: 'Говорю, что больше никогда не буду есть.' },
      { id: 'C', es: 'Tiro toda la compra.', ru: 'Выбрасываю все остальные покупки.' },
      { id: 'D', es: 'Rompo la lista.', ru: 'Рву список покупок.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Volver a comprarlo» — пойти и снова купить. Конструкция «volver a + infinitivo» означает повторить действие.',
    prizeMoney: 1000,
  },
  {
    id: 48,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Presente',
    tenseExplanationRu: 'Compras (покупаешь) / cuesta (стоит) — Presente.',
    questionEs: 'Compras un queso de 5 euros y un zumo de 3 euros. ¿Cuánto cuesta en total?',
    questionRu: 'Ты покупаешь сыр за 5 евро и сок за 3 евро. Сколько это стоит всего?',
    options: [
      { id: 'A', es: '2 euros.', ru: '2 евро.' },
      { id: 'B', es: '6 euros.', ru: '6 евро.' },
      { id: 'C', es: '8 euros.', ru: '8 евро.' },
      { id: 'D', es: '15 euros.', ru: '15 евро.' },
    ],
    correctAnswer: 'C',
    explanationRu: '5 + 3 = 8 евро («ocho euros en total»).',
    prizeMoney: 2000,
  },
  {
    id: 49,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Pretérito Perfecto',
    tenseExplanationRu: 'Has abierto (ты открыл, abrir — нерегулярное abierto) / compraste (купил) / ves (видишь) — времена прошедшее и настоящее.',
    questionEs: 'Has abierto una fruta que compraste ayer y ves que está en mal estado. ¿Qué haces?',
    questionRu: 'Ты открыл фрукт, купленный вчера, и видишь, что он испорчен. Что ты делаешь?',
    options: [
      { id: 'A', es: 'No lo como y compruebo los demás.', ru: 'Не ем его и проверяю остальные фрукты.' },
      { id: 'B', es: 'Me lo como rápido.', ru: 'Быстро съедаю его.' },
      { id: 'C', es: 'Lo pongo otra vez en el supermercado.', ru: 'Отношу и тайно кладу обратно на полку магазина.' },
      { id: 'D', es: 'Bebo dos litros de agua.', ru: 'Пью два литра воды.' },
    ],
    correctAnswer: 'A',
    explanationRu: '«Estar en mal estado» — быть испорченным. Разумно не употреблять такой продукт («no lo como»).',
    prizeMoney: 3000,
  },
  {
    id: 50,
    category: 'supermercado',
    categoryTitleEs: '🛒 Supermercado',
    categoryTitleRu: 'Супермаркет',
    tense: 'Presente',
    tenseExplanationRu: 'Estás (находишься) / faltan (не хватает) / elijo (выбираю, elegir e -> i) / pago (плачу) — Presente.',
    questionEs: 'Estás en la caja y te faltan dos euros para pagar toda la compra. ¿Qué haces?',
    questionRu: 'Ты на кассе, и тебе не хватает двух евро, чтобы оплатить всю покупку. Что ты делаешь?',
    options: [
      { id: 'A', es: 'Elijo qué producto puedo dejar y pago lo demás.', ru: 'Выбираю, какой товар можно оставить, и оплачиваю остальное.' },
      { id: 'B', es: 'Salgo corriendo con todo.', ru: 'Убегаю со всеми покупками.' },
      { id: 'C', es: 'Pido al cajero que pague mi comida.', ru: 'Требую, чтобы кассир заплатил за меня.' },
      { id: 'D', es: 'Lloro en el suelo.', ru: 'Плачу на полу.' },
    ],
    correctAnswer: 'A',
    explanationRu: 'Если не хватает денег, вежливо просят убрать один товар («dejar un producto»): кассир отменит позицию.',
    prizeMoney: 5000,
  },
];
